"""Plain-English tender briefs.

If an OpenAI-compatible LLM key is configured (``LLM_API_KEY`` plus optional
``LLM_BASE_URL`` / ``LLM_MODEL``), briefs are generated by the model.
Otherwise a deterministic template brief is produced.  The caller always
knows which path was taken via ``brief_source`` — template briefs are
labelled as such in the UI and are never presented as AI output.
"""

from __future__ import annotations

import os
from datetime import date

import requests

from tenders import Tender


def llm_configured() -> bool:
    return bool(os.environ.get("LLM_API_KEY", ""))


def _inr(value: int | None) -> str:
    if value is None:
        return "not stated"
    if value >= 10_000_000:
        return f"₹{value / 10_000_000:.2f} Cr"
    if value >= 100_000:
        return f"₹{value / 100_000:.2f} Lakh"
    return f"₹{value:,}"


def template_brief(tender: Tender, today: date | None = None) -> str:
    """Deterministic, clearly-labelled brief — no LLM needed."""
    today = today or date.today()
    lines = [
        f"## {tender.title}",
        "",
        f"**Issued by:** {tender.authority} via {tender.portal or 'the tender portal'}",
    ]
    if tender.location:
        lines.append(f"**Location:** {tender.location}")
    lines.append(f"**Category:** {tender.category}")
    lines.append(f"**Estimated value:** {_inr(tender.value_inr)}")
    lines.append(f"**Earnest money (EMD):** {_inr(tender.emd_inr)}")
    days = tender.days_to_deadline(today)
    if tender.bid_due_date:
        due = tender.bid_due_date.strftime("%d %b %Y")
        if days is not None and days >= 0:
            lines.append(f"**Bid due:** {due} ({days} days left)")
        else:
            lines.append(f"**Bid due:** {due} (deadline passed)")
    else:
        lines.append("**Bid due:** not stated in the listing — verify on the portal")
    lines += [
        "",
        "### Why this could matter to you",
    ]
    if tender.match_reasons:
        lines += [f"- {r}" for r in tender.match_reasons]
    else:
        lines.append("- Review the scope below and compare it with your capabilities.")
    lines += [
        "",
        "### Before you bid",
        "- Read the full tender document on the portal for eligibility, "
        "technical specs and payment terms.",
        "- Confirm the EMD amount and acceptable instruments (DD / bank guarantee).",
        "- Check whether MSME / NSIC / Startup-India exemptions apply to you.",
        "- Note the bid submission mode (online only vs. physical) and any "
        "pre-bid meeting dates.",
    ]
    if tender.url:
        lines += ["", f"[Open the original tender listing]({tender.url})"]
    return "\n".join(lines)


def llm_brief(tender: Tender) -> str:
    """Generate a brief with a configured OpenAI-compatible chat API."""
    api_key = os.environ["LLM_API_KEY"]
    base_url = os.environ.get("LLM_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.environ.get("LLM_MODEL", "gpt-4o-mini")
    prompt = (
        "You are a tender analyst helping an Indian small business owner. "
        "Write a concise plain-English brief (under 220 words) for this public tender.\n\n"
        f"Title: {tender.title}\n"
        f"Authority: {tender.authority}\n"
        f"Portal: {tender.portal}\n"
        f"Location: {tender.location or 'not stated'}\n"
        f"Category: {tender.category}\n"
        f"Estimated value (INR): {tender.value_inr or 'not stated'}\n"
        f"EMD (INR): {tender.emd_inr or 'not stated'}\n"
        f"Bid due date: {tender.bid_due_date or 'not stated'}\n"
        f"Listing snippet: {tender.snippet[:600]}\n\n"
        "Structure: 1) one-line summary, 2) key facts as bullets, "
        "3) 'why it matters' for an SMB, 4) a 4-item bid-readiness checklist. "
        "No markdown tables. No invented dates or amounts — say 'not stated' "
        "when the data is missing."
    )
    resp = requests.post(
        f"{base_url}/chat/completions",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.3,
            "max_tokens": 500,
        },
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def generate_brief(tender: Tender, today: date | None = None) -> tuple[str, str]:
    """Return (brief_markdown, source) where source is 'llm' or 'template'."""
    if llm_configured():
        try:
            return llm_brief(tender), "llm"
        except Exception:  # noqa: BLE001 - fall back to template on any failure
            pass
    return template_brief(tender, today), "template"
